package io.watermelon.ci.manifest.compile;

import io.watermelon.ci.manifest.model.DeploySpec;
import io.watermelon.ci.manifest.model.DockerPublishSpec;
import io.watermelon.ci.manifest.model.JobSpec;
import io.watermelon.ci.manifest.model.MavenPublishSpec;
import io.watermelon.ci.manifest.model.PipelineManifest;
import io.watermelon.ci.manifest.model.PublishSpec;
import io.watermelon.ci.manifest.model.WhenPolicy;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

/**
 * Compiles a GitLab-CI style Watermelon manifest into a Declarative Jenkinsfile.
 * Users never write Groovy — the platform owns the safe translation.
 */
@Component
public class JenkinsfileCompiler {

    public CompiledPipeline compile(PipelineManifest manifest, CompileContext ctx) {
        String jobName = ctx.organizationSlug() + "-" + ctx.projectSlug() + "-" + sanitize(manifest.getName());
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Watermelon CI — do not edit manually\n");
        sb.append("pipeline {\n");
        sb.append("  agent none\n");
        sb.append("  options { timestamps(); disableConcurrentBuilds(); buildDiscarder(logRotator(numToKeepStr: '50')) }\n");
        sb.append("  environment {\n");
        sb.append("    WM_PIPELINE_RUN_ID = '").append(escape(ctx.pipelineRunId())).append("'\n");
        sb.append("    WM_REGISTRY = '").append(escape(ctx.registryHost())).append("'\n");
        sb.append("    WM_MAVEN_REPO = '").append(escape(nullToEmpty(ctx.mavenRepositoryUrl()))).append("'\n");
        sb.append("    WM_PROJECT = '").append(escape(ctx.projectSlug())).append("'\n");
        sb.append("    WM_PROJECT_ID = '").append(escape(nullToEmpty(ctx.projectId()))).append("'\n");
        sb.append("    WM_PLATFORM_URL = '").append(escape(nullToEmpty(ctx.platformUrl()))).append("'\n");
        if (manifest.getVariables() != null) {
            for (Map.Entry<String, String> e : manifest.getVariables().entrySet()) {
                sb.append("    ").append(sanitizeEnv(e.getKey())).append(" = '").append(escape(e.getValue())).append("'\n");
            }
        }
        sb.append("  }\n");
        sb.append("  stages {\n");

        for (String stage : manifest.getStages()) {
            sb.append("    stage('").append(escape(stage)).append("') {\n");
            List<Map.Entry<String, JobSpec>> stageJobs = manifest.getJobs().entrySet().stream()
                    .filter(e -> stage.equals(e.getValue().getStage()))
                    .collect(Collectors.toCollection(ArrayList::new));
            if (stageJobs.isEmpty()) {
                sb.append("      steps { echo 'no jobs in stage' }\n");
            } else if (stageJobs.size() == 1) {
                appendJob(sb, stageJobs.getFirst().getKey(), stageJobs.getFirst().getValue(), ctx);
            } else {
                sb.append("      parallel {\n");
                for (var entry : stageJobs) {
                    sb.append("        stage('").append(escape(entry.getKey())).append("') {\n");
                    appendJob(sb, entry.getKey(), entry.getValue(), ctx);
                    sb.append("        }\n");
                }
                sb.append("      }\n");
            }
            sb.append("    }\n");
        }

        appendPublishStage(sb, manifest.getPublish(), ctx);
        sb.append("  }\n");
        sb.append("}\n");
        return new CompiledPipeline(jobName, sb.toString());
    }

    private void appendJob(StringBuilder sb, String jobName, JobSpec job, CompileContext ctx) {
        String image = job.getImage() != null ? job.getImage() : "eclipse-temurin:21";
        sb.append("      agent { docker { image '").append(escape(image)).append("'; reuseNode true } }\n");
        if (job.getWhen() == WhenPolicy.MANUAL) {
            sb.append("      steps {\n");
            sb.append("        input message: 'Manual approval for ").append(escape(jobName)).append("'\n");
        } else {
            sb.append("      steps {\n");
        }
        for (String line : job.getScript()) {
            sb.append("        sh '''").append(escapeTriple(line)).append("'''\n");
        }
        if (job.getDeploy() != null) {
            appendDeploy(sb, job, ctx);
        }
        sb.append("      }\n");
    }

    private void appendDeploy(StringBuilder sb, JobSpec job, CompileContext ctx) {
        DeploySpec deploy = job.getDeploy();
        String env = job.getEnvironment() != null ? job.getEnvironment() : "default";
        String image = deploy.getImage() != null ? deploy.getImage() : "${WM_REGISTRY}/${WM_PROJECT}:latest";
        String release = deploy.getRelease() != null ? deploy.getRelease() : ctx.projectSlug() + "-" + env;
        sb.append("        sh '''\n");
        sb.append("set -euo pipefail\n");
        sb.append("echo \"[watermelon] deploy runtime=")
                .append(deploy.getRuntime().name().toLowerCase())
                .append(" env=")
                .append(escape(env))
                .append(" track=")
                .append(deploy.isTrack())
                .append("\"\n");
        switch (deploy.getRuntime()) {
            case DOCKER -> {
                sb.append("docker pull ").append(escape(image)).append(" || true\n");
                sb.append("docker rm -f ").append(escape(release)).append(" 2>/dev/null || true\n");
                sb.append("CID=$(docker run -d --name ").append(escape(release));
                sb.append(" --label watermelon.ci/pipeline-run=${WM_PIPELINE_RUN_ID}");
                sb.append(" --label watermelon.ci/project=${WM_PROJECT}");
                sb.append(" --label watermelon.ci/environment=").append(escape(env));
                sb.append(" --label watermelon.ci/track=").append(deploy.isTrack() ? "true" : "false");
                if (deploy.getPorts() != null) {
                    for (String p : deploy.getPorts()) {
                        sb.append(" -p ").append(escape(p));
                    }
                }
                sb.append(" ").append(escape(image)).append(")\n");
                sb.append("echo \"[watermelon] container=$CID\"\n");
                if (deploy.isTrack()) {
                    sb.append("curl -fsS -X POST \"${WM_PLATFORM_URL}/api/v1/runtime/agent/heartbeat\" ");
                    sb.append("-H \"Content-Type: application/json\" ");
                    sb.append("-d \"{\\\"pipelineRunId\\\":\\\"${WM_PIPELINE_RUN_ID}\\\",");
                    sb.append("\\\"externalId\\\":\\\"${CID}\\\",");
                    sb.append("\\\"environment\\\":\\\"").append(escape(env)).append("\\\",");
                    sb.append("\\\"imageRef\\\":\\\"").append(escape(image)).append("\\\",");
                    sb.append("\\\"releaseName\\\":\\\"").append(escape(release)).append("\\\",");
                    sb.append("\\\"status\\\":\\\"HEALTHY\\\"}\" || true\n");
                }
            }
            case COMPOSE -> sb.append("docker compose up -d --pull always\n");
            case KUBERNETES -> {
                sb.append("kubectl set image deployment/")
                        .append(escape(release))
                        .append(" app=")
                        .append(escape(image))
                        .append(" --record\n");
                sb.append("kubectl rollout status deployment/").append(escape(release)).append("\n");
            }
            case ARGOCD -> {
                sb.append("curl -fsS -X POST \"${WM_PLATFORM_URL}/api/v1/projects/${WM_PROJECT_ID}/gitops/deploy\" ");
                sb.append("-H \"Content-Type: application/json\" ");
                sb.append("-d \"{\\\"environment\\\":\\\"").append(escape(env)).append("\\\",");
                sb.append("\\\"release\\\":\\\"").append(escape(release)).append("\\\",");
                sb.append("\\\"image\\\":\\\"").append(escape(image)).append("\\\",");
                sb.append("\\\"replicas\\\":").append(Math.max(1, deploy.getReplicas())).append(",");
                sb.append("\\\"namespace\\\":\\\"").append(escape(deploy.getNamespace() != null ? deploy.getNamespace() : "")).append("\\\",");
                sb.append("\\\"secrets\\\":[");
                if (deploy.getSecrets() != null && !deploy.getSecrets().isEmpty()) {
                    for (int i = 0; i < deploy.getSecrets().size(); i++) {
                        if (i > 0) {
                            sb.append(',');
                        }
                        sb.append("\\\"").append(escape(deploy.getSecrets().get(i))).append("\\\"");
                    }
                }
                sb.append("],");
                sb.append("\\\"ports\\\":[");
                if (deploy.getPorts() != null && !deploy.getPorts().isEmpty()) {
                    for (int i = 0; i < deploy.getPorts().size(); i++) {
                        if (i > 0) {
                            sb.append(',');
                        }
                        sb.append("\\\"").append(escape(deploy.getPorts().get(i))).append("\\\"");
                    }
                }
                sb.append("]}\"\n");
            }
        }
        sb.append("'''\n");
    }

    private void appendPublishStage(StringBuilder sb, PublishSpec publish, CompileContext ctx) {
        if (publish == null) {
            return;
        }
        boolean hasDocker = publish.getDocker() != null && !publish.getDocker().isEmpty();
        boolean hasMaven = publish.getMaven() != null && publish.getMaven().isDeploy();
        if (!hasDocker && !hasMaven) {
            return;
        }
        sb.append("    stage('publish') {\n");
        sb.append("      agent { label 'docker' }\n");
        sb.append("      steps {\n");
        if (hasDocker) {
            for (DockerPublishSpec docker : publish.getDocker()) {
                List<String> tags = docker.getTags().isEmpty() ? List.of("latest") : docker.getTags();
                String image = docker.getImage();
                sb.append("        sh '''\n");
                sb.append("set -euo pipefail\n");
                sb.append("docker build -f ")
                        .append(escape(docker.getDockerfile()))
                        .append(" -t ")
                        .append(escape(ctx.registryHost()))
                        .append("/")
                        .append(escape(image))
                        .append(":")
                        .append(escape(tags.getFirst()))
                        .append(" ")
                        .append(escape(docker.getContext()))
                        .append("\n");
                for (String tag : tags) {
                    String full = ctx.registryHost() + "/" + image + ":" + tag;
                    sb.append("docker tag ")
                            .append(escape(ctx.registryHost()))
                            .append("/")
                            .append(escape(image))
                            .append(":")
                            .append(escape(tags.getFirst()))
                            .append(" ")
                            .append(escape(full))
                            .append("\n");
                    sb.append("docker push ").append(escape(full)).append("\n");
                }
                sb.append("'''\n");
            }
        }
        if (hasMaven) {
            MavenPublishSpec maven = publish.getMaven();
            String goals = String.join(" ", maven.getGoals().isEmpty() ? List.of("deploy") : maven.getGoals());
            sb.append("        sh '''\n");
            sb.append("./mvnw -B ")
                    .append(escape(goals))
                    .append(" -DaltDeploymentRepository=watermelon::default::${WM_MAVEN_REPO}\n");
            sb.append("'''\n");
        }
        sb.append("      }\n");
        sb.append("    }\n");
    }

    private static String sanitize(String raw) {
        return raw.toLowerCase().replaceAll("[^a-z0-9-]", "-").replaceAll("-{2,}", "-");
    }

    private static String sanitizeEnv(String raw) {
        return raw.toUpperCase().replaceAll("[^A-Z0-9_]", "_");
    }

    private static String escape(String raw) {
        return nullToEmpty(raw).replace("\\", "\\\\").replace("'", "\\'");
    }

    private static String escapeTriple(String raw) {
        return nullToEmpty(raw).replace("'''", "'\\''");
    }

    private static String nullToEmpty(String raw) {
        return raw == null ? "" : raw;
    }
}
